on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install
        run:  npm install
      - name: build
        run:  npm run build
      - name: lint
        run:  npm run lint
      - name: Publish
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release')
        uses: decentraland/oddish-action@0074f2d535c43b5c83f136525304a6277166d77f # @master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
